openapi: 3.0.1
info:
  title: BankFileConverter
  description: An API to convert excel file(s) into bank file format.
  contact:
    name: Louis Cochinho
    url: https://github.com/lscchnh
    email: louis.cochinho@hotmail.fr
  version: v1
paths:
  /BankFileConverter/file:
    post:
      tags:
        - BankFileConverter
      summary: Convert excel file(s) content to the specified output bank file format.
      parameters:
        - name: inputPath
          in: query
          description: The path to the repertory containing the input excel files.
          required: true
          schema:
            type: string
            description: The path to the repertory containing the input excel files.
        - name: outputPath
          in: query
          description: The path to the repertory containing the output bank files.
          schema:
            type: string
            description: The path to the repertory containing the output bank files.
            nullable: true
        - name: inputFileType
          in: query
          description: The input file type.
          schema:
            $ref: '#/components/schemas/InputFileType'
        - name: outputFileType
          in: query
          description: The output bank file format.
          schema:
            $ref: '#/components/schemas/OutputFileType'
        - name: onlyTransactions
          in: query
          description: 'If true, the excel file is only containing transactions amount. If false, it is only containing amounts.'
          schema:
            type: boolean
            description: 'If true, the excel file is only containing transactions amount. If false, it is only containing amounts.'
            default: true
        - name: initialAmount
          in: query
          description: An initial amount on which starting transactions in QIF file.
          schema:
            type: number
            description: An initial amount on which starting transactions in QIF file.
            format: float
            default: 0
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                type: string
                format: binary
        '400':
          description: 'BadRequest : invalid url provided or empty excel file(s).'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: No excel file(s) found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error.
        '501':
          description: Not implemented.
components:
  schemas:
    InputFileType:
      enum:
        - ANY
        - EDENRED
        - CREDITFR
        - COINBASE
      type: string
    OutputFileType:
      enum:
        - QIF
        - OFX
      type: string
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }